// <auto-generated />
using System;
using BloodDonation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloodDonation.Migrations
{
    [DbContext(typeof(DonationContext))]
    [Migration("20190502141645_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("BloodDonation.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<string>("DonorPesel");

                    b.HasKey("Id");

                    b.HasIndex("DonorPesel");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("BloodDonation.Models.Donor", b =>
                {
                    b.Property<string>("Pesel")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BloodGroup");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName");

                    b.Property<int>("Rh");

                    b.HasKey("Pesel");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("BloodDonation.Models.Donation", b =>
                {
                    b.HasOne("BloodDonation.Models.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorPesel");
                });
#pragma warning restore 612, 618
        }
    }
}
